version: '3.8'

services:
  fastapi:
    container_name: book_management
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    container_name: prod_db
    environment:
      POSTGRES_DB: book_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 10
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
